backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "project"
    label: "Project"
    folder: "src/pages/project"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: Image, name: image, widget: image }
      - { label: URL, name: url, widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "array" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        widget: "object"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - {
              label: About,
              name: about,
              widget: object,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Title, name: title, widget: string },
                  { label: Blurb, name: blurb, widget: text },
                ],
            }
          - label: "Info"
            name: "info"
            widget: "list"
            fields:
              - { label: Icon, name: icon, widget: "string" }
              - { label: Href, name: href, widget: "string" }
              - { label: Text, name: text, widget: "string" }
          - label: "Skills"
            name: "skills"
            widget: "object"
            fields:
              [
                {
                  label: Toolset,
                  name: toolSet,
                  widget: list,
                  summary: '{{fields.name}}: {{fields.value}}',
                  fields:
                    [
                      { label: Name, name: name, widget: string },
                      { label: Value, name: value, widget: number },
                      { label: Size, name: size, widget: select, options: ["lg", "md", "sm"] }
                    ],
                },                
                {
                  label: Skill Set,
                  name: skillSet,
                  widget: list,
                  summary: '{{fields.name}}: {{fields.value}}',
                  fields:
                    [
                      { label: Name, name: name, widget: string },
                      { label: Value, name: value, widget: number }
                    ],
                },
                { label: Code, name: code, hint: 'comma separated', widget: text },
                { label: Languages, name: languages, hint: 'comma separated', widget: text },
              ]
          - label: "Education"
            name: "education"
            widget: "list"
            fields:
              - { label: "Title", name: title, widget: "string" }
              - { label: "Start Date", name: startDate, widget: "string", required: false }
              - { label: "End Date", name: endDate, widget: "string", required: false }
              - { label: "Sub Title", name: subTitle, widget: "string" }
              - { label: "Descriptions", name: descriptions, widget: "markdown", required: false }
          - label: "Jobs"
            name: "jobs"
            widget: "list"
            fields:
              - { label: "Job Title", name: jobTitle, widget: "string" }
              - { label: "Start Date", name: startDate, widget: "string" }
              - { label: "End Date", name: endDate, widget: "string" }
              - { label: "Work Place", name: workPlace, widget: "string" }
              - { label: "Descriptions", name: descriptions, widget: "markdown", required: false }
          - label: "Highlights"
            name: "highlights"
            widget: "list"
            fields:
              - { label: "Title", name: title, widget: "string" }
              - { label: "Start Date", name: startDate, widget: "string", required: false }
              - { label: "End Date", name: endDate, widget: "string", required: false }
              - { label: "Sub Title", name: subTitle, widget: "string" }
              - { label: "Descriptions", name: descriptions, widget: "markdown", required: false }
          - label: "Volunteer"
            name: "volunteer"
            widget: "list"
            fields:
              - { label: "Title", name: title, widget: "string" }
              - { label: "Start Date", name: startDate, widget: "string", required: false }
              - { label: "End Date", name: endDate, widget: "string", required: false }
              - { label: "Sub Title", name: subTitle, widget: "string" }
              - { label: "Descriptions", name: descriptions, widget: "markdown", required: false }
          
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
